spring.application.name=AtividadePratica

#Configs banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/atividade_pratica?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=uninter123

#JPA
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true
spring.jpa.open-in-view= true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

